spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backenddata
    username: root
    password: raju
  jpa:
#    databasePlatform: org.hibernate.dialect.MySQL8InnoDBDialect
    generateDdl: true
    showSql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernates:
        globally_quoted_indentifiers: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never